// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen -source=handlers.go -destination=./mocks/service_mock.go -package=mocks -mock_names=storage=ServiceMock Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "JacFARM/internal/http/dto"
	models "JacFARM/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddTeam mocks base method.
func (m *MockService) AddTeam(ctx context.Context, team *models.Team) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", ctx, team)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockServiceMockRecorder) AddTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*MockService)(nil).AddTeam), ctx, team)
}

// DeleteExploit mocks base method.
func (m *MockService) DeleteExploit(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExploit", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExploit indicates an expected call of DeleteExploit.
func (mr *MockServiceMockRecorder) DeleteExploit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExploit", reflect.TypeOf((*MockService)(nil).DeleteExploit), ctx, id)
}

// DeleteTeam mocks base method.
func (m *MockService) DeleteTeam(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *MockServiceMockRecorder) DeleteTeam(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*MockService)(nil).DeleteTeam), ctx, id)
}

// GetConfig mocks base method.
func (m *MockService) GetConfig(ctx context.Context, filter *dto.GetConfigFilter) ([]*models.Config, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, filter)
	ret0, _ := ret[0].([]*models.Config)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockServiceMockRecorder) GetConfig(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockService)(nil).GetConfig), ctx, filter)
}

// GetFlagsCount mocks base method.
func (m *MockService) GetFlagsCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlagsCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlagsCount indicates an expected call of GetFlagsCount.
func (mr *MockServiceMockRecorder) GetFlagsCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlagsCount", reflect.TypeOf((*MockService)(nil).GetFlagsCount), ctx)
}

// GetStatuses mocks base method.
func (m *MockService) GetStatuses(ctx context.Context) ([]*models.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatuses", ctx)
	ret0, _ := ret[0].([]*models.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatuses indicates an expected call of GetStatuses.
func (mr *MockServiceMockRecorder) GetStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatuses", reflect.TypeOf((*MockService)(nil).GetStatuses), ctx)
}

// ListExploits mocks base method.
func (m *MockService) ListExploits(ctx context.Context, filter *dto.ListExploitsFilter) ([]*models.Exploit, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExploits", ctx, filter)
	ret0, _ := ret[0].([]*models.Exploit)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExploits indicates an expected call of ListExploits.
func (mr *MockServiceMockRecorder) ListExploits(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExploits", reflect.TypeOf((*MockService)(nil).ListExploits), ctx, filter)
}

// ListFlags mocks base method.
func (m *MockService) ListFlags(ctx context.Context, filter *dto.ListFlagsFilter) ([]*models.FlagEnrich, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlags", ctx, filter)
	ret0, _ := ret[0].([]*models.FlagEnrich)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFlags indicates an expected call of ListFlags.
func (mr *MockServiceMockRecorder) ListFlags(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlags", reflect.TypeOf((*MockService)(nil).ListFlags), ctx, filter)
}

// ListLogLevel mocks base method.
func (m *MockService) ListLogLevel(ctx context.Context) ([]*models.LogLevel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogLevel", ctx)
	ret0, _ := ret[0].([]*models.LogLevel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLogLevel indicates an expected call of ListLogLevel.
func (mr *MockServiceMockRecorder) ListLogLevel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogLevel", reflect.TypeOf((*MockService)(nil).ListLogLevel), ctx)
}

// ListLogs mocks base method.
func (m *MockService) ListLogs(ctx context.Context, filter *dto.ListLogsFilter) ([]*models.Log, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogs", ctx, filter)
	ret0, _ := ret[0].([]*models.Log)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLogs indicates an expected call of ListLogs.
func (mr *MockServiceMockRecorder) ListLogs(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogs", reflect.TypeOf((*MockService)(nil).ListLogs), ctx, filter)
}

// ListModules mocks base method.
func (m *MockService) ListModules(ctx context.Context) ([]*models.Module, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModules", ctx)
	ret0, _ := ret[0].([]*models.Module)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModules indicates an expected call of ListModules.
func (mr *MockServiceMockRecorder) ListModules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModules", reflect.TypeOf((*MockService)(nil).ListModules), ctx)
}

// ListShortExploits mocks base method.
func (m *MockService) ListShortExploits(ctx context.Context) ([]*models.ExploitShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShortExploits", ctx)
	ret0, _ := ret[0].([]*models.ExploitShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShortExploits indicates an expected call of ListShortExploits.
func (mr *MockServiceMockRecorder) ListShortExploits(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShortExploits", reflect.TypeOf((*MockService)(nil).ListShortExploits), ctx)
}

// ListShortTeams mocks base method.
func (m *MockService) ListShortTeams(ctx context.Context) ([]*models.ShortTeam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShortTeams", ctx)
	ret0, _ := ret[0].([]*models.ShortTeam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShortTeams indicates an expected call of ListShortTeams.
func (mr *MockServiceMockRecorder) ListShortTeams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShortTeams", reflect.TypeOf((*MockService)(nil).ListShortTeams), ctx)
}

// ListTeams mocks base method.
func (m *MockService) ListTeams(ctx context.Context, filter *dto.ListTeamsFilter) ([]*models.Team, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeams", ctx, filter)
	ret0, _ := ret[0].([]*models.Team)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTeams indicates an expected call of ListTeams.
func (mr *MockServiceMockRecorder) ListTeams(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeams", reflect.TypeOf((*MockService)(nil).ListTeams), ctx, filter)
}

// PutFlag mocks base method.
func (m *MockService) PutFlag(ctx context.Context, flag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutFlag", ctx, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutFlag indicates an expected call of PutFlag.
func (mr *MockServiceMockRecorder) PutFlag(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutFlag", reflect.TypeOf((*MockService)(nil).PutFlag), ctx, flag)
}

// ServicePutFlag mocks base method.
func (m *MockService) ServicePutFlag(ctx context.Context, req *dto.ServicePutFlagRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServicePutFlag", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServicePutFlag indicates an expected call of ServicePutFlag.
func (mr *MockServiceMockRecorder) ServicePutFlag(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServicePutFlag", reflect.TypeOf((*MockService)(nil).ServicePutFlag), ctx, req)
}

// ToggleExploit mocks base method.
func (m *MockService) ToggleExploit(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleExploit", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleExploit indicates an expected call of ToggleExploit.
func (mr *MockServiceMockRecorder) ToggleExploit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleExploit", reflect.TypeOf((*MockService)(nil).ToggleExploit), ctx, id)
}

// UpdateConfig mocks base method.
func (m *MockService) UpdateConfig(ctx context.Context, id int64, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockServiceMockRecorder) UpdateConfig(ctx, id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockService)(nil).UpdateConfig), ctx, id, value)
}

// UploadExploit mocks base method.
func (m *MockService) UploadExploit(ctx context.Context, req *dto.UploadExploitRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadExploit", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadExploit indicates an expected call of UploadExploit.
func (mr *MockServiceMockRecorder) UploadExploit(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadExploit", reflect.TypeOf((*MockService)(nil).UploadExploit), ctx, req)
}
