services:
  db:
    hostname: db
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  flag_queue:
    hostname: flag_queue
    image: rabbitmq:4.1.2
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 5672:5672
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq