services:
  flag_queue:
    hostname: flag_queue
    image: rabbitmq:4.1.2
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 5672:5672
    volumes:
      - ./rabbitmq_volume:/var/lib/rabbitmq