CREATE SCHEMA IF NOT EXISTS audit;

CREATE TABLE IF NOT EXISTS audit.log_levels (
    id SERIAL PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS audit.services (
    id SERIAL PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS audit.events (
    id SERIAL PRIMARY KEY,
    level_id INT NOT NULL REFERENCES audit.log_levels(id),
    type VARCHAR(32) NOT NULL,
    message TEXT NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL
);