FROM rabbitmq:4.1.2-management

RUN apt-get update && apt-get install -y unzip wget

RUN wget https://github.com/noxdafox/rabbitmq-message-deduplication/releases/download/0.7.1/plugins-rmqv4.1.x-erl27-elx1.18.zip -O /tmp/dedup_plugin.zip
RUN unzip /tmp/dedup_plugin.zip -d /tmp/extracted_plugin
RUN mv /tmp/extracted_plugin/* /opt/rabbitmq/plugins

RUN rabbitmq-plugins enable --offline rabbitmq_message_deduplication