// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./mocks/storage_mock.go -package=mocks -mock_names=storage=StorageMock storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "JacFARM/internal/http/dto"
	models "JacFARM/internal/models"
	rabbitmq_dto "JacFARM/pkg/rabbitmq_dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// StorageMock is a mock of storage interface.
type StorageMock struct {
	ctrl     *gomock.Controller
	recorder *StorageMockMockRecorder
	isgomock struct{}
}

// StorageMockMockRecorder is the mock recorder for StorageMock.
type StorageMockMockRecorder struct {
	mock *StorageMock
}

// NewStorageMock creates a new mock instance.
func NewStorageMock(ctrl *gomock.Controller) *StorageMock {
	mock := &StorageMock{ctrl: ctrl}
	mock.recorder = &StorageMockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StorageMock) EXPECT() *StorageMockMockRecorder {
	return m.recorder
}

// AddTeam mocks base method.
func (m *StorageMock) AddTeam(ctx context.Context, team *models.Team) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", ctx, team)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTeam indicates an expected call of AddTeam.
func (mr *StorageMockMockRecorder) AddTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*StorageMock)(nil).AddTeam), ctx, team)
}

// CreateExploit mocks base method.
func (m *StorageMock) CreateExploit(ctx context.Context, exploit *models.Exploit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExploit", ctx, exploit)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExploit indicates an expected call of CreateExploit.
func (mr *StorageMockMockRecorder) CreateExploit(ctx, exploit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExploit", reflect.TypeOf((*StorageMock)(nil).CreateExploit), ctx, exploit)
}

// DeleteExploit mocks base method.
func (m *StorageMock) DeleteExploit(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExploit", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExploit indicates an expected call of DeleteExploit.
func (mr *StorageMockMockRecorder) DeleteExploit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExploit", reflect.TypeOf((*StorageMock)(nil).DeleteExploit), ctx, id)
}

// DeleteTeam mocks base method.
func (m *StorageMock) DeleteTeam(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *StorageMockMockRecorder) DeleteTeam(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*StorageMock)(nil).DeleteTeam), ctx, id)
}

// GetConfig mocks base method.
func (m *StorageMock) GetConfig(ctx context.Context, filter *dto.GetConfigFilter) ([]*models.Config, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, filter)
	ret0, _ := ret[0].([]*models.Config)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *StorageMockMockRecorder) GetConfig(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*StorageMock)(nil).GetConfig), ctx, filter)
}

// GetExploits mocks base method.
func (m *StorageMock) GetExploits(ctx context.Context, filter *dto.ListExploitsFilter) ([]*models.Exploit, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExploits", ctx, filter)
	ret0, _ := ret[0].([]*models.Exploit)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetExploits indicates an expected call of GetExploits.
func (mr *StorageMockMockRecorder) GetExploits(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExploits", reflect.TypeOf((*StorageMock)(nil).GetExploits), ctx, filter)
}

// GetFlags mocks base method.
func (m *StorageMock) GetFlags(ctx context.Context, filter *dto.ListFlagsFilter) ([]*models.FlagEnrich, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlags", ctx, filter)
	ret0, _ := ret[0].([]*models.FlagEnrich)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFlags indicates an expected call of GetFlags.
func (mr *StorageMockMockRecorder) GetFlags(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlags", reflect.TypeOf((*StorageMock)(nil).GetFlags), ctx, filter)
}

// GetShortExploits mocks base method.
func (m *StorageMock) GetShortExploits(ctx context.Context) ([]*models.ExploitShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortExploits", ctx)
	ret0, _ := ret[0].([]*models.ExploitShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortExploits indicates an expected call of GetShortExploits.
func (mr *StorageMockMockRecorder) GetShortExploits(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortExploits", reflect.TypeOf((*StorageMock)(nil).GetShortExploits), ctx)
}

// GetShortTeams mocks base method.
func (m *StorageMock) GetShortTeams(ctx context.Context) ([]*models.ShortTeam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortTeams", ctx)
	ret0, _ := ret[0].([]*models.ShortTeam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortTeams indicates an expected call of GetShortTeams.
func (mr *StorageMockMockRecorder) GetShortTeams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortTeams", reflect.TypeOf((*StorageMock)(nil).GetShortTeams), ctx)
}

// GetStatuses mocks base method.
func (m *StorageMock) GetStatuses(ctx context.Context) ([]*models.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatuses", ctx)
	ret0, _ := ret[0].([]*models.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatuses indicates an expected call of GetStatuses.
func (mr *StorageMockMockRecorder) GetStatuses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatuses", reflect.TypeOf((*StorageMock)(nil).GetStatuses), ctx)
}

// GetTeams mocks base method.
func (m *StorageMock) GetTeams(ctx context.Context, filter *dto.ListTeamsFilter) ([]*models.Team, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeams", ctx, filter)
	ret0, _ := ret[0].([]*models.Team)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTeams indicates an expected call of GetTeams.
func (mr *StorageMockMockRecorder) GetTeams(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeams", reflect.TypeOf((*StorageMock)(nil).GetTeams), ctx, filter)
}

// ListLogLevel mocks base method.
func (m *StorageMock) ListLogLevel(ctx context.Context) ([]*models.LogLevel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogLevel", ctx)
	ret0, _ := ret[0].([]*models.LogLevel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLogLevel indicates an expected call of ListLogLevel.
func (mr *StorageMockMockRecorder) ListLogLevel(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogLevel", reflect.TypeOf((*StorageMock)(nil).ListLogLevel), ctx)
}

// ListLogs mocks base method.
func (m *StorageMock) ListLogs(ctx context.Context, filter *dto.ListLogsFilter) ([]*models.Log, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogs", ctx, filter)
	ret0, _ := ret[0].([]*models.Log)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLogs indicates an expected call of ListLogs.
func (mr *StorageMockMockRecorder) ListLogs(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogs", reflect.TypeOf((*StorageMock)(nil).ListLogs), ctx, filter)
}

// ListModules mocks base method.
func (m *StorageMock) ListModules(ctx context.Context) ([]*models.Module, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModules", ctx)
	ret0, _ := ret[0].([]*models.Module)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListModules indicates an expected call of ListModules.
func (mr *StorageMockMockRecorder) ListModules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModules", reflect.TypeOf((*StorageMock)(nil).ListModules), ctx)
}

// ToggleExploit mocks base method.
func (m *StorageMock) ToggleExploit(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleExploit", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleExploit indicates an expected call of ToggleExploit.
func (mr *StorageMockMockRecorder) ToggleExploit(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleExploit", reflect.TypeOf((*StorageMock)(nil).ToggleExploit), ctx, id)
}

// UpdateConfigRow mocks base method.
func (m *StorageMock) UpdateConfigRow(ctx context.Context, id int64, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigRow", ctx, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfigRow indicates an expected call of UpdateConfigRow.
func (mr *StorageMockMockRecorder) UpdateConfigRow(ctx, id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigRow", reflect.TypeOf((*StorageMock)(nil).UpdateConfigRow), ctx, id, value)
}

// Mockqueue is a mock of queue interface.
type Mockqueue struct {
	ctrl     *gomock.Controller
	recorder *MockqueueMockRecorder
	isgomock struct{}
}

// MockqueueMockRecorder is the mock recorder for Mockqueue.
type MockqueueMockRecorder struct {
	mock *Mockqueue
}

// NewMockqueue creates a new mock instance.
func NewMockqueue(ctrl *gomock.Controller) *Mockqueue {
	mock := &Mockqueue{ctrl: ctrl}
	mock.recorder = &MockqueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockqueue) EXPECT() *MockqueueMockRecorder {
	return m.recorder
}

// GetFlagsCount mocks base method.
func (m *Mockqueue) GetFlagsCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlagsCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlagsCount indicates an expected call of GetFlagsCount.
func (mr *MockqueueMockRecorder) GetFlagsCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlagsCount", reflect.TypeOf((*Mockqueue)(nil).GetFlagsCount))
}

// PublishFlag mocks base method.
func (m *Mockqueue) PublishFlag(flag *rabbitmq_dto.Flag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFlag", flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFlag indicates an expected call of PublishFlag.
func (mr *MockqueueMockRecorder) PublishFlag(flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFlag", reflect.TypeOf((*Mockqueue)(nil).PublishFlag), flag)
}
