// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source=worker.go -destination=./mocks/worker_mock.go -package=mocks -mock_names=storage=WorkerMock Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	jacfarm "jacfarmcli/internal/clients/jacfarm"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJacFARMClient is a mock of JacFARMClient interface.
type MockJacFARMClient struct {
	ctrl     *gomock.Controller
	recorder *MockJacFARMClientMockRecorder
	isgomock struct{}
}

// MockJacFARMClientMockRecorder is the mock recorder for MockJacFARMClient.
type MockJacFARMClientMockRecorder struct {
	mock *MockJacFARMClient
}

// NewMockJacFARMClient creates a new mock instance.
func NewMockJacFARMClient(ctrl *gomock.Controller) *MockJacFARMClient {
	mock := &MockJacFARMClient{ctrl: ctrl}
	mock.recorder = &MockJacFARMClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJacFARMClient) EXPECT() *MockJacFARMClientMockRecorder {
	return m.recorder
}

// GetTeams mocks base method.
func (m *MockJacFARMClient) GetTeams(ctx context.Context) ([]*jacfarm.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeams", ctx)
	ret0, _ := ret[0].([]*jacfarm.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeams indicates an expected call of GetTeams.
func (mr *MockJacFARMClientMockRecorder) GetTeams(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeams", reflect.TypeOf((*MockJacFARMClient)(nil).GetTeams), ctx)
}

// SendFlags mocks base method.
func (m *MockJacFARMClient) SendFlags(ctx context.Context, flags []*jacfarm.ServiceFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFlags", ctx, flags)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFlags indicates an expected call of SendFlags.
func (mr *MockJacFARMClientMockRecorder) SendFlags(ctx, flags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFlags", reflect.TypeOf((*MockJacFARMClient)(nil).SendFlags), ctx, flags)
}
